# SPDX-FileCopyrightText: Alliander N. V.
# 
# SPDX-License-Identifier: Apache-2.0

services:
  franka:
    image: franka
    container_name: franka
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:/home/rcdt/.vscode-server"
      - "../.devcontainer:/home/rcdt/.devcontainer"
      - "../.git:/home/rcdt/.git"
      - "../.github:/home/rcdt/.github"
      - "../dockerfiles:/home/rcdt/dockerfiles"
      - "../LICENSES:/home/rcdt/LICENSES"
      - "../ros2_ws:/home/rcdt/ros2_ws"
      - "../.bashrc.personal:/home/rcdt/.bashrc.personal"
      - "../.gitignore:/home/rcdt/.gitignore"
      - "../CODE_OF_CONDUCT.md:/home/rcdt/CODE_OF_CONDUCT.md"
      - "../CONTRIBUTING.md:/home/rcdt/CONTRIBUTING.md"
      - "../PROJECT_GOVERNANCE.md:/home/rcdt/PROJECT_GOVERNANCE.md"
      - "../pyproject.toml:/home/rcdt/pyproject.toml"
      - "../README.md:/home/rcdt/README.md"
      - "../run:/home/rcdt/run"
      - "/dev:/dev"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
  mobile_manipulator:
    image: mobile_manipulator
    container_name: mobile_manipulator
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:/home/rcdt/.vscode-server"
      - "../.devcontainer:/home/rcdt/.devcontainer"
      - "../.git:/home/rcdt/.git"
      - "../.github:/home/rcdt/.github"
      - "../dockerfiles:/home/rcdt/dockerfiles"
      - "../LICENSES:/home/rcdt/LICENSES"
      - "../ros2_ws:/home/rcdt/ros2_ws"
      - "../.bashrc.personal:/home/rcdt/.bashrc.personal"
      - "../.gitignore:/home/rcdt/.gitignore"
      - "../CODE_OF_CONDUCT.md:/home/rcdt/CODE_OF_CONDUCT.md"
      - "../CONTRIBUTING.md:/home/rcdt/CONTRIBUTING.md"
      - "../PROJECT_GOVERNANCE.md:/home/rcdt/PROJECT_GOVERNANCE.md"
      - "../pyproject.toml:/home/rcdt/pyproject.toml"
      - "../README.md:/home/rcdt/README.md"
      - "../run:/home/rcdt/run"
      - "/dev/input:/dev/input"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
  panther:
    image: panther
    container_name: panther
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:/home/rcdt/.vscode-server"
      - "../.devcontainer:/home/rcdt/.devcontainer"
      - "../.git:/home/rcdt/.git"
      - "../.github:/home/rcdt/.github"
      - "../dockerfiles:/home/rcdt/dockerfiles"
      - "../LICENSES:/home/rcdt/LICENSES"
      - "../ros2_ws:/home/rcdt/ros2_ws"
      - "../.bashrc.personal:/home/rcdt/.bashrc.personal"
      - "../.gitignore:/home/rcdt/.gitignore"
      - "../CODE_OF_CONDUCT.md:/home/rcdt/CODE_OF_CONDUCT.md"
      - "../CONTRIBUTING.md:/home/rcdt/CONTRIBUTING.md"
      - "../PROJECT_GOVERNANCE.md:/home/rcdt/PROJECT_GOVERNANCE.md"
      - "../pyproject.toml:/home/rcdt/pyproject.toml"
      - "../README.md:/home/rcdt/README.md"
      - "../run:/home/rcdt/run"
      - "/dev/input:/dev/input"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
  ros2:
    image: ros2
    container_name: ros2
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.vscode-server:/home/rcdt/.vscode-server"
      - "../.devcontainer:/home/rcdt/.devcontainer"
      - "../.git:/home/rcdt/.git"
      - "../.github:/home/rcdt/.github"
      - "../dockerfiles:/home/rcdt/dockerfiles"
      - "../LICENSES:/home/rcdt/LICENSES"
      - "../ros2_ws:/home/rcdt/ros2_ws"
      - "../.bashrc.personal:/home/rcdt/.bashrc.personal"
      - "../.gitignore:/home/rcdt/.gitignore"
      - "../CODE_OF_CONDUCT.md:/home/rcdt/CODE_OF_CONDUCT.md"
      - "../CONTRIBUTING.md:/home/rcdt/CONTRIBUTING.md"
      - "../PROJECT_GOVERNANCE.md:/home/rcdt/PROJECT_GOVERNANCE.md"
      - "../pyproject.toml:/home/rcdt/pyproject.toml"
      - "../README.md:/home/rcdt/README.md"
      - "../run:/home/rcdt/run"
    environment:
      - "DISPLAY"
      - "RCUTILS_COLORIZED_OUTPUT=1"
      - NVIDIA_VISIBLE_DEVICES=all
